/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CalculatorResult {
  'emi' : number,
  'gst' : number,
  'totalDeductions' : number,
  'processingFee' : number,
  'netDisbursal' : number,
  'totalRepayment' : number,
  'totalInterest' : number,
  'tenureYears' : number,
  'insurance' : number,
  'totalMonths' : number,
  'amount' : number,
}
export interface UpdateParams {
  'insurancePer1000' : [] | [number],
  'processingFeeRate' : [] | [number],
  'numberOfPersons' : [] | [bigint],
  'interestRate' : [] | [number],
  'gstRate' : [] | [number],
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'calculateLoan' : ActorMethod<[number, number], CalculatorResult>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getParameters' : ActorMethod<
    [],
    {
      'insurancePer1000' : number,
      'processingFeeRate' : number,
      'numberOfPersons' : bigint,
      'interestRate' : number,
      'gstRate' : number,
    }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateParameters' : ActorMethod<[UpdateParams], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];