/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CalculatorResult = IDL.Record({
  'emi' : IDL.Float64,
  'gst' : IDL.Float64,
  'totalDeductions' : IDL.Float64,
  'processingFee' : IDL.Float64,
  'netDisbursal' : IDL.Float64,
  'totalRepayment' : IDL.Float64,
  'totalInterest' : IDL.Float64,
  'tenureYears' : IDL.Float64,
  'insurance' : IDL.Float64,
  'totalMonths' : IDL.Float64,
  'amount' : IDL.Float64,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const UpdateParams = IDL.Record({
  'insurancePer1000' : IDL.Opt(IDL.Float64),
  'processingFeeRate' : IDL.Opt(IDL.Float64),
  'numberOfPersons' : IDL.Opt(IDL.Nat),
  'interestRate' : IDL.Opt(IDL.Float64),
  'gstRate' : IDL.Opt(IDL.Float64),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'calculateLoan' : IDL.Func(
      [IDL.Float64, IDL.Float64],
      [CalculatorResult],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getParameters' : IDL.Func(
      [],
      [
        IDL.Record({
          'insurancePer1000' : IDL.Float64,
          'processingFeeRate' : IDL.Float64,
          'numberOfPersons' : IDL.Nat,
          'interestRate' : IDL.Float64,
          'gstRate' : IDL.Float64,
        }),
      ],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateParameters' : IDL.Func([UpdateParams], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CalculatorResult = IDL.Record({
    'emi' : IDL.Float64,
    'gst' : IDL.Float64,
    'totalDeductions' : IDL.Float64,
    'processingFee' : IDL.Float64,
    'netDisbursal' : IDL.Float64,
    'totalRepayment' : IDL.Float64,
    'totalInterest' : IDL.Float64,
    'tenureYears' : IDL.Float64,
    'insurance' : IDL.Float64,
    'totalMonths' : IDL.Float64,
    'amount' : IDL.Float64,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const UpdateParams = IDL.Record({
    'insurancePer1000' : IDL.Opt(IDL.Float64),
    'processingFeeRate' : IDL.Opt(IDL.Float64),
    'numberOfPersons' : IDL.Opt(IDL.Nat),
    'interestRate' : IDL.Opt(IDL.Float64),
    'gstRate' : IDL.Opt(IDL.Float64),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'calculateLoan' : IDL.Func(
        [IDL.Float64, IDL.Float64],
        [CalculatorResult],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getParameters' : IDL.Func(
        [],
        [
          IDL.Record({
            'insurancePer1000' : IDL.Float64,
            'processingFeeRate' : IDL.Float64,
            'numberOfPersons' : IDL.Nat,
            'interestRate' : IDL.Float64,
            'gstRate' : IDL.Float64,
          }),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateParameters' : IDL.Func([UpdateParams], [], []),
  });
};

export const init = ({ IDL }) => { return []; };